package com.scraper.platform.repository;

import com.scraper.platform.model.CompanyBlacklist;
import com.scraper.platform.model.CrawlConfig;
import com.scraper.platform.model.JobPosting;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.autoconfigure.jdbc.AutoConfigureTestDatabase;
import org.springframework.boot.test.autoconfigure.orm.jpa.DataJpaTest;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;

import javax.sql.DataSource;
import java.sql.Connection;
import java.sql.Statement;
import java.time.LocalDate;
import java.util.List;
import java.util.UUID;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * 설계 036 JPA 슬라이스 게이트.
 * searchRecent JPQL(2중 NOT EXISTS + REPLACE 체인)은 repository 부팅 시 파싱되므로
 * 컨텍스트 기동만으로 파싱 오류를 잡는다. 실제 실행으로 exact/contains 차단 필터,
 * 소유권 필터, 키워드/사이트 필터, 네이티브 LIKE 카운트까지 H2로 검증한다.
 * ddl-auto=none + 수동 DDL — 엔티티 columnDefinition(MEDIUMTEXT/JSON)과
 * 인덱스 prefix(url(191))는 H2 스키마 생성 대상이 아니므로 회피한다.
 */
@DataJpaTest(properties = {
        "spring.jpa.hibernate.ddl-auto=none",
        "spring.datasource.url=jdbc:h2:mem:scraper-jpa-test;DB_CLOSE_DELAY=-1",
        "spring.datasource.driver-class-name=org.h2.Driver",
        "spring.datasource.username=sa",
        "spring.datasource.password="
})
@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)
@DisplayName("JobPostingRepository JPA 슬라이스 (설계 036 — searchRecent 게이트)")
class JobPostingRepositoryDataJpaTest {

    @Autowired
    private JobPostingRepository jobPostingRepository;

    @Autowired
    private CompanyBlacklistRepository blacklistRepository;

    @Autowired
    private com.scraper.platform.repository.CrawlConfigRepository configRepository;

    @Autowired
    private DataSource dataSource;

    private static final Long ACCOUNT = 1L;
    private static final Long OTHER = 2L;

    @BeforeEach
    void setUpSchema() throws Exception {
        try (Connection c = dataSource.getConnection(); Statement s = c.createStatement()) {
            s.execute("DROP TABLE IF EXISTS job_postings");
            s.execute("DROP TABLE IF EXISTS company_blacklist");
            s.execute("DROP TABLE IF EXISTS crawl_config");
            s.execute("""
                    CREATE TABLE crawl_config (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account_id BIGINT NOT NULL,
                        name VARCHAR(100) NOT NULL,
                        description CLOB,
                        schedule VARCHAR(500),
                        retention_days INT,
                        is_active BOOLEAN,
                        email_notification BOOLEAN,
                        push_notification BOOLEAN,
                        recipient_email VARCHAR(200),
                        local_path VARCHAR(500),
                        schedule_icon VARCHAR(10),
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                    )
                    """);
            s.execute("""
                    CREATE TABLE job_postings (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        config_id BIGINT,
                        saved_by_account_id BIGINT,
                        site_name VARCHAR(50) NOT NULL,
                        url VARCHAR(500) NOT NULL,
                        company VARCHAR(200) NOT NULL,
                        position VARCHAR(300) NOT NULL,
                        career VARCHAR(100),
                        tech VARCHAR(500),
                        location VARCHAR(200),
                        deadline VARCHAR(100),
                        dedup_key VARCHAR(64) NOT NULL,
                        crawl_log_id BIGINT,
                        crawled_at DATE NOT NULL,
                        created_at TIMESTAMP,
                        updated_at TIMESTAMP
                    )
                    """);
            s.execute("""
                    CREATE TABLE company_blacklist (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        account_id BIGINT NOT NULL,
                        company_name_normalized VARCHAR(200) NOT NULL,
                        match_type VARCHAR(20) NOT NULL,
                        reason VARCHAR(200),
                        created_at TIMESTAMP
                    )
                    """);
        }
    }

    private JobPosting posting(String site, String company, Long savedBy, CrawlConfig config) {
        return JobPosting.builder()
                .siteName(site)
                .url("https://example.com/j/" + UUID.randomUUID())
                .company(company)
                .position("Java 개발자")
                .dedupKey(UUID.randomUUID().toString())
                .crawledAt(LocalDate.of(2026, 9, 20))
                .savedByAccountId(savedBy)
                .config(config)
                .build();
    }

    private List<String> companies(Page<JobPosting> page) {
        return page.getContent().stream().map(JobPosting::getCompany).toList();
    }

    @Test
    @DisplayName("exact/contains 차단 필터 + 소유권 필터가 SQL에서 함께 적용된다")
    void searchRecent_차단_소유권_필터() {
        // 내 소유 (savedBy) — exact 차단 대상
        jobPostingRepository.saveAndFlush(posting("saramin", "삼성전자", ACCOUNT, null));
        jobPostingRepository.saveAndFlush(posting("saramin", "삼성전자(주)", ACCOUNT, null));
        // contains 차단 대상 (부분 일치)
        jobPostingRepository.saveAndFlush(posting("saramin", "악덕기업", ACCOUNT, null));
        // 차단 안 됨 → 결과에 포함
        jobPostingRepository.saveAndFlush(posting("saramin", "네이버", ACCOUNT, null));
        // 타인 소유 → 제외
        jobPostingRepository.saveAndFlush(posting("saramin", "카카오", OTHER, null));
        // config 경로 소유 (내 config) → 포함
        CrawlConfig myConfig = configRepository.saveAndFlush(
                CrawlConfig.builder().accountId(ACCOUNT).name("내설정").build());
        jobPostingRepository.saveAndFlush(posting("saramin", "포스코", null, myConfig));
        // config 경로 타인 소유 → 제외
        CrawlConfig otherConfig = configRepository.saveAndFlush(
                CrawlConfig.builder().accountId(OTHER).name("남설정").build());
        jobPostingRepository.saveAndFlush(posting("saramin", "LG전자", null, otherConfig));

        // 차단: exact "삼성전자" (원문 변형 삼성전자(주) 포함), contains "악덕"
        blacklistRepository.saveAndFlush(CompanyBlacklist.builder()
                .accountId(ACCOUNT).companyNameNormalized("삼성전자")
                .matchType(CompanyBlacklist.MatchType.exact).build());
        blacklistRepository.saveAndFlush(CompanyBlacklist.builder()
                .accountId(ACCOUNT).companyNameNormalized("악덕")
                .matchType(CompanyBlacklist.MatchType.contains).build());

        var page = jobPostingRepository.searchRecent(ACCOUNT, null, null,
                CompanyBlacklist.MatchType.exact, CompanyBlacklist.MatchType.contains,
                PageRequest.of(0, 20));
        List<String> result = companies(page);

        assertEquals(2, page.getTotalElements(), "차단·타인 소유 제외 후 2건: " + result);
        assertTrue(result.contains("네이버"), String.valueOf(result));
        assertTrue(result.contains("포스코"), String.valueOf(result));
        assertFalse(result.contains("삼성전자"), "exact 차단 실패: " + result);
        assertFalse(result.contains("삼성전자(주)"), "정규화(REPLACE) exact 차단 실패: " + result);
        assertFalse(result.contains("악덕기업"), "contains 차단 실패: " + result);
        assertFalse(result.contains("카카오"), "타인 소유 제외 실패: " + result);
        assertFalse(result.contains("LG전자"), "타인 config 소유 제외 실패: " + result);
    }

    @Test
    @DisplayName("키워드·사이트 필터가 차단 필터와 함께 적용된다")
    void searchRecent_키워드_사이트_필터() {
        jobPostingRepository.saveAndFlush(posting("saramin", "네이버", ACCOUNT, null));
        jobPostingRepository.saveAndFlush(posting("jobkorea", "현대차", ACCOUNT, null));

        var byKeyword = jobPostingRepository.searchRecent(ACCOUNT, "네이", null,
                CompanyBlacklist.MatchType.exact, CompanyBlacklist.MatchType.contains,
                PageRequest.of(0, 20));
        assertEquals(List.of("네이버"), companies(byKeyword));

        var bySite = jobPostingRepository.searchRecent(ACCOUNT, null, "jobkorea",
                CompanyBlacklist.MatchType.exact, CompanyBlacklist.MatchType.contains,
                PageRequest.of(0, 20));
        assertEquals(List.of("현대차"), companies(bySite));

        var noHit = jobPostingRepository.searchRecent(ACCOUNT, "없는키워드", null,
                CompanyBlacklist.MatchType.exact, CompanyBlacklist.MatchType.contains,
                PageRequest.of(0, 20));
        assertEquals(0, noHit.getTotalElements());
    }

    @Test
    @DisplayName("차단 항목이 없어도 쿼리는 정상 실행된다 (빠른 경로 아님 — 항상 NOT EXISTS)")
    void searchRecent_차단목록_없음() {
        jobPostingRepository.saveAndFlush(posting("saramin", "네이버", ACCOUNT, null));

        var page = jobPostingRepository.searchRecent(ACCOUNT, null, null,
                CompanyBlacklist.MatchType.exact, CompanyBlacklist.MatchType.contains,
                PageRequest.of(0, 20));

        assertEquals(1, page.getTotalElements());
    }

    @Test
    @DisplayName("countByNormalizedCompanyContaining 네이티브 LIKE 카운트가 정규화 기준이다")
    void countByNormalizedCompanyContaining_정규화_카운트() {
        jobPostingRepository.saveAndFlush(posting("saramin", "삼성전자", ACCOUNT, null));
        jobPostingRepository.saveAndFlush(posting("saramin", "삼성전자(주)", ACCOUNT, null));
        jobPostingRepository.saveAndFlush(posting("saramin", "네이버", ACCOUNT, null));

        assertEquals(2, jobPostingRepository.countByNormalizedCompanyContaining("삼성"));
        assertEquals(1, jobPostingRepository.countByNormalizedCompanyContaining("네이"));
        assertEquals(0, jobPostingRepository.countByNormalizedCompanyContaining("없는회사"));
    }
}
