server:
  port: 8082
  error:
    whitelabel:
      enabled: false

spring:
  application:
    name: resume-platform
  datasource:
    url: jdbc:mariadb://10.0.0.39:3306/resume_platform?useSSL=false&allowPublicKeyRetrieval=true
    username: sh_user
    password: SHpass1234!
    driver-class-name: org.mariadb.jdbc.Driver
    hikari:
      maximum-pool-size: 5
      minimum-idle: 2
      max-lifetime: 1800000
      idle-timeout: 600000
      connection-timeout: 30000
      leak-detection-threshold: 30000
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate:
        format_sql: false
  jackson:
    default-property-inclusion: non_null

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /api-docs-ui
    operationsSorter: method

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: when-authorized
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true

jwt:
  public-key: ${JWT_PUBLIC_KEY:-----BEGIN PUBLIC KEY-----MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAxkUEb22qrrg6+oR7RNfWGOCzfMLACJvYiY6QUaEjY9BWoPMlt2QNiB8Pqqt75rTAINtMc7LBFsNN3jL7WsLsxU0TH1QJaNhgTnSERijpTVPaH+iOozsUWqMyEpaqnVCwzm673XPWPYyexPbDL4bF5gI57Z99nQS24Dq76hk6ok384ut/j0CzUn7IKDf33ENvsIbQkp1ICwBc4iKKSr8TnfMCcSpScWdYWo4aU+h+hR1x7aNkX9Qx7g/nL4YBafiq7Ubw35MWTdohFlENXyK7VNS+YWHbi67JyMGvVKcAG/AtJwtWBTFLUYp4wzo5CDfGQBEV8/ujehVdb/TryAlY9wIDAQAB-----END PUBLIC KEY-----}

logging:
  file:
    path: ${LOG_PATH:logs}
  level:
    root: INFO
    com.shplatform.resume: INFO
