spring:
  datasource:
    url: jdbc:h2:mem:shplatform
    driver-class-name: org.h2.Driver
    username: sa
    password:

  jpa:
    hibernate:
      ddl-auto: create-drop
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

jwt:
  private-key: |
    -----BEGIN PRIVATE KEY-----
    MIIJQgIBADANBgkqhkiG9w0BAQEFAASCCSwwggkoAgEAAoICAQDQlzG9VjWHWKGw
    P7d7y9kZPmJxJw+n5LIOgJwRoSFTFVEEeF/QmBHEr45Pnk+1ZCdTLFcnG+xJYlSQ
    guF1qNJ8A6RqRY9LWNcPmWAV/mXJGBqWEDRnjvCn7vx3/AufahN+cPPccl2oN+kJ
    5oHSMbJ9G0LksqlC34An7Bn0NiSUylAs7HTFBUvr2J9hFoClIVIMYXBnVdMiKxFq
    FEYTIGdq4k+ajsPEq0h4FzMw+Jz9NMFn4Fm+8+QbYFzSvLRQ7UW4sBmtQyDPqGcE
    3RRsKJgrEBaOq+o3jZ43NqCWgK5Nk1K5g/TEko2yjjL3lgSNYLFLBmvABqgF1n3S
    L90w7Yx78dK/GhldqEOT5Wxn6/Hu6DD5fHt7+Q/qPNGLIuDfG8kqVLEe6MzgSQah
    TbuGRKf09wl5+RjMLUFZpfyWMgRS5bRC7b69/aPKZtIDZqH0CDq3dpvMkbNWsz/s
    Cs1ZAY1rmHACGRF5G5YvvNsi88aCGL5VQ30YvhSqCzJ5mH8C+nqgzFx7jKvpN8yp
    7wn5eRNqMImhxjQq5XnqMv3pfs0Q4SiAFQFCnrPmMZv8VdCnAm55HARjAQ4cOvhm
    LkuJ4m1blM56+jR9DQMiGslHE4Me9b1Zq/kjzGEIJD7Ca52q9dys/EOkqHg8ESn2
    u4WHnO+0X9THe06YCN8O7fnBtN44IV1HrQIDAQABAoICAH8YkAmfCdT6QaOWYDhn
    1DvT9fJk4t9n8X79yKTM6T0HkWcAjop9bQ5Y/xTGRQEXYcrJ4ldPCYOjKxQEXnsU
    ZnE+URb+QO9jMGH8+QB/eH7R+Wj2/mJSkCfC3t0vYsf0d8r8tRGK7I5wPQRcAcI0
    W9L9kJNW+Kq6nzNmBLgKk20tH6BjAFnxA+yNxRl2g8cMVa9VhjfMCBXK0GsSWqI3
    3pzW1ZLsWgqk4sAsFcpPDRs2B/HML3EWGqFOQ8+IS5vASRZ76xhV8G+7MFr8T3IY
    F5r2HXG5r3NDVWSK5eFnFaNj7BHS3YWV4NKZX3K97ETWKv9QD1LL4jAtm3We2nMY
    2gNx9AZxNB7cZpnQEsHjo8u8Kq01x5v4SOgAFNCNwsSCjYlxBK9avxQZ1FwOqJYk
    5+0C4xUifBkjX/r5RsnPg6FuIBZy8kXWnPRQ9vVYR4KGJnQpmgRCyY3OV/3x7Ddg
    zPsLDqdqSV4aVvG+P6zn/pRoigMmfUfn4djHzM5nB4ixAQP+vp6bQQsHcI4i3UE2
    pP7WHgv9PZ5D1pqIltUu3UwBvNIAZRhiA+Ucn0xhJhbCGBWeWW2nk7ssmtqkMTQl
    DHwMmMo4GiypsY4i2lLPZzcmIQxZ3QNyAZ6RN2qytnw8xX35X1BDFzB+H1b3C4JG
    FTp2nEQ5sUq2wb/QU8knERqqGiAQTeA9AoIBAQD+w34tAxa7j5NQNQ2VvCr/VWJE
    LaFI53nq6qBlq5ZljT+RqYlH9V5/g8MUC64h8YVE2iQ7n37vHLN4He4QqkbbidCz
    zjj1q3WsfMkS5hb6pOVjBT5jDLxAL/1LQe5phOT9sV6xBnVfn6sYPORfFoCBKQjH
    2C34bxStRbbLADQTBKc/C9BNjYFPMI7rCa+99EhnBwhiWynV4VUzEjA75uL+QN0l
    pRCBsTAsfRFIKWYYcf7r3dFwBJLheAHf5FQHE7lFnAWIlDMmkfNp8XwFo6NfWBeX
    81KLyVRQFmyNwZ1AA3V+VLgXW77s0w2t86t5g4N/2H2NCmIlO6ULmN4cC1y/AoIB
    AQDQlzG9VjWHWKGwP7d7y9kZPmJxJw+n5LIOgJwRoSFTFVEEeF/QmBHEr45Pnk+1
    ZCdTLFcnG+xJYlSQguF1qNJ8A6RqRY9LWNcPmWAV/mXJGBqWEDRnjvCn7vx3/Auf
    ahN+cPPccl2oN+kJ5oHSMbJ9G0LksqlC34An7Bn0NiSUylAs7HTFBUvr2J9hFoCl
    IVIMYXBnVdMiKxFqFEYTIGdq4k+ajsPEq0h4FzMw+Jz9NMFn4Fm+8+QbYFzSvLRQ
    7UW4sBmtQyDPqGcE3RRsKJgrEBaOq+o3jZ43NqCWgK5Nk1K5g/TEko2yjjL3lgSN
    YLFLBmvABqgF1n3SL90w7Yx78dK/GhldqEOT5Wxn6/Hu6DD5fHt7+Q/qPNGLIuDf
    G8kqVLEe6MzgSQahTbuGRKf09wl5+RjMLUFZpfyWMgRS5bRC7b69/aPKZtIDZqH0
    CDq3dpvMkbNWsz/sCs1ZAY1rmHACGRF5G5YvvNsi88aCGL5VQ30YvhSqCzJ5mH8C
    +nqgzFx7jKvpN8yp7wn5eRNqMImhxjQq5XnqMv3pfs0Q4SiAFQFCnrPmMZv8VdCn
    Am55HARjAQ4cOvhmLkuJ4m1blM56+jR9DQMiGslHE4Me9b1Zq/kjzGEIJD7Ca52q
    9dys/EOkqHg8ESn2u4WHnO+0X9THe06YCN8O7fnBtN44IV1HrQIDAQABAoICAH8Y
    kAmfCdT6QaOWYDhn1DvT9fJk4t9n8X79yKTM6T0HkWcAjop9bQ5Y/xTGRQEXYcrJ
    4ldPCYOjKxQEXnsUZnE+URb+QO9jMGH8+QB/eH7R+Wj2/mJSkCfC3t0vYsf0d8r8
    tRGK7I5wPQRcAcI0W9L9kJNW+Kq6nzNmBLgKk20tH6BjAFnxA+yNxRl2g8cMVa9V
    hjfMCBXK0GsSWqI33pzW1ZLsWgqk4sAsFcpPDRs2B/HML3EWGqFOQ8+IS5vASRZ7
    6xhV8G+7MFr8T3IYF5r2HXG5r3NDVWSK5eFnFaNj7BHS3YWV4NKZX3K97ETWKv9Q
    D1LL4jAtm3We2nMY2gNx9AZxNB7cZpnQEsHjo8u8Kq01x5v4SOgAFNCNwsSCjYlx
    BK9avxQZ1FwOqJYk5+0C4xUifBkjX/r5RsnPg6FuIBZy8kXWnPRQ9vVYR4KGJnQp
    mgRCyY3OV/3x7DdgzPsLDqdqSV4aVvG+P6zn/pRoigMmfUfn4djHzM5nB4ixAQP+
    vp6bQQsHcI4i3UE2pP7WHgv9PZ5D1pqIltUu3UwBvNIAZRhiA+Ucn0xhJhbCGBWe
    WW2nk7ssmtqkMTQlDHwMmMo4GiypsY4i2lLPZzcmIQxZ3QNyAZ6RN2qytnw8xX35
    X1BDFzB+H1b3C4JGFTp2nEQ5sUq2wb/QU8knERqqGiAQTeA9AoIBAQD2Zq2W2vMy
    /eZQaCUGrPjlRkY/xrr1+cx7z0FYX5RZHaFfk5C5Lf9r9W4IiohN+TsOHPFw7zOh
    a0p60CjRyLpJ6F0UA8WUS8tXc2Xg4ex7O1mIzbMcRt9BuqMht6WKVJFb/koLwY9/
    vRwO1t89zG8Qlg3n84vYWLYHghzO33IeQ92YQS9GQzHbE77BYZzRNJG05lz3+J1W
    Kq60GF8nqY35hb6Oza7d92oG6AYMC8n5QfL7ip7+0sOn8PqnqF4LpG2O3rXMppBO
    gP5pKv1bJs3tvy0zHhyV6NB2M3WVRqg+WkGFhWFDhYGFORFf8v42//ChIpY9ldZR
    Gr5aPP6D88sOePc3ggH/AoIBAQDvaKXTUikWG3bIWl3V6E78kYxM/on/CaBMDV9o
    rnLq48ldO+PPqwFG48eO0dRbc2te01iAEQLHgsbt78K1Y8r6qftf2tpAPPsyBq0X
    ilc4t3+ffmYKnYQ3A1ek6ztv0V8X3sLl6dJtGnXe+TUmsSxBfONGoXxEIFq+snle
    hgF+rDIFRqrjhybPPfYI5Vq8LiCiRvrIp0QpG5VHE/sKxfgkFu81UXICRhQvft5p
    skPHbLLMvX9PHNMuFNbPX28zFiZPEBQ+qihobk70wK7rIlr6b5/M4qILFXQhJG7N
    6qxpHEfFGSUEIKMLHxiU4teZq5prPsMFQm+5vMBeSgB7+4sRAoIBADi++QAM25Xn
    41Yq2o9QK/FxnWvYx+8dMauyqYvMr4f3Sqt/58vjjx7wNvDIsfQCI2fY6Dk+FtO1
    M4wdHITSCjbNMF5Yh5mWLr6kMJv8aZQjjBgk/6MAgNkY1aFzW8EBOR7q0q60LqyR
    gmJf/7vqQGE05IDj6ewRmL5w7Y0/OTGBNjfTvfCOo37+LbHiMG+2Bw5q5IL8+Jmw
    Hp7nypA7sK8tMQWMqD8VVxWNMksN7Dy/cA9t4Hq3cOGm3/GQIQ73DHO0ot0/hVb5
    P7wfFnUKYw5yN4t45UvGpcnqQ5zPBgl55ryvUjNBj8CIAgRzl8WzBDXj02k6jXwG
    5Jxnr7V5CIECggEAeQyHr2mHhq1IfyqqkVqUxXFjN4rvMKWFXGH11WjV6W1P1dQy
    6XqFnYVIMfV4n95WR1m5vI9yZ1ZOVs4z4+DLXhdQ4tQlE5plxFyjEyR2NVFF0UTa
    bqCZu+GN8v6CHNZFcm+EUOz5s17qWWG+X6h7v5kqCSDW7vLV6lAjbINjVQMkNYdT
    IjGfhZ9TpQY4rmqLix4fXyG+RThYFoMGBmPNQAh8WF92aPxsb52z0NqVSlVHALF0
    1gRGq9NPb+WUB8mchUtVFVWqBcOAHh4syJJgK5bX6DBoFGWJhBpsqK6ILl4pLmFW
    QPZq0fKn4bHkzH4WFwZDpm0tKMGGqInLh47tYjtg3A==
    -----END PRIVATE KEY-----

  public-key: |
    -----BEGIN PUBLIC KEY-----
    MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA0JcxvVY1h1ihsD+3e8vZ
    GT5icScPp+SyDoCcEaEhUxVRBHhf0JgRxK+OT55PtWQnUyxXJxvsSWJUkILhdajS
    fAOkakWPS1jXD5lgFf5lyRgalhA0Z47wp+78d/wLn2oTfnDz3HJdqDfpCeaB0jGy
    fRtC5LKpQt+AJ+wZ9DYklMpQLOx0xQVL69ifYRaApSFSDGFwZ1XTIisRahRGEyBn
    auJPmo7DxKtIeBczMPic/TTBZ+BZvvPkG2Bc0ry0UO1FuLAZrUMgz6hnBN0UbCiY
    KxAWjqvqN42eNzagloCuTZNSuYP0xJKNso4y95YEjWCxSwZrwAaoBdZ90i/dMO2M
    e/HSvxoZXahDk+VsZ+vx7ugw+Xx7e/kP6jzRiyLg3xvJKlSxHujM4EkGoU27hkSn
    9PcJefkYzC1BWaX8ljIEUuW0Qu2+vf2jymbSA2ah9Ag6t3abzJGzVrM/7ArNWQGN
    a5hwAhkReRuWL7zbIvPGghi+VUN9GL4UqgsyeZh/Avp6oMxce4yr6TfMqe8J+XkT
    ajCIocY0KuV56jL96X7NEOEogBUBQp6z5jGb/FXQpwJueRwEYwEOHDr4Zi5LieJt
    W5TOevo0fQ0DIhrJRxODHvW9Wav5I8xhCCQ+wmudqvXcrPxDpKh4PBEp9ruFh5zv
    tF/Ux3tOmAjfDu35wbTeOCFdR60CAwEAAQ==
    -----END PUBLIC KEY-----

  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000
